### ISSUE TITLE
Ignores custom uri pattern

### ISSUE THREAD

**Issue by gerhard-boden** [techdivision/TechDivision.NotFound#1]
I have this entry in my `Configuration/Routes.yaml`:

```
  name: 'Filter Hotel'
  uriPattern: 'filter-hotels'
  defaults:
    '@package': 'ACME.Package'
    '@controller': 'Frontend\HotelFilter'
    '@action': 'filter'
```

When i activate the plugin, `filter-hotels` will return the 404 page. 

Can you confirm this bug?

**Comment by dittertp** [comment]
HI,

have you tried to change the position of your custom route (above the 404 route)? I've tested the package with a lot of additional routes an never see any problem like that.

**Comment by gerhard-boden** [comment]
Hi, 
thank you for your fast response!
I tried taking out the route from the package and i put it in the same file like my custom routes, but it did not help anything. When i completly leave out the route and delete the NodeNotFoundRoutePartHandler, the plugin works just the same.

**Comment by gerhard-boden** [comment]
Update:
turns out when i put the

```
-
  name: 'TYPO3 Neos'
  uriPattern: '<TYPO3NeosSubroutes>'
  subRoutes:
    'TYPO3NeosSubroutes':
      package: 'TYPO3.Neos'
      variables:
        'defaultUriSuffix': ''
```

route at the very end  everything is working fine! I can even do without the custom 404 route and without the `NodeNotFoundRoutePartHandler`. Or does it do something that i'm not seeing?

Thanks for the plugin!
