### ISSUE TITLE
Neos 2.2 RedirectHandler will not be called, if Plugin is enabled

### ISSUE THREAD

**Issue by belliconag** [techdivision/TechDivision.NotFound#5]
There is an issue with TechDivision.NotFound and the RedirectHandler of Neos 2.2 where the RedirectHandler was never called because TechDivision.NotFound was executed before the RedirectHandler.

RedirectHandler: https://github.com/neos/redirecthandler

A quick solution is to execute the RedirectHandler "before routing" instead of "after routing", where the "NotFound" handler already took over the handling.

So, if you come into this issue, simply set the "position" to "before routing".

```
  Flow:
    http:       
      chain:
        'process':
          chain:
            'redirect':
              position: 'before routing' # Fix: Execute before TechDivision.NotFound (FrontEndRouteHandlerAspect).
              component: 'Neos\RedirectHandler\RedirectComponent'
```

But beware, the RedirectHandler is made for "after routing". It seems to work, but eventually the plugins could be running side by side without hacks like this.

Are you considering to look into this issue?

Thanks
